### ISSUE TITLE
TransformingVcfLineParserTest.simpleIntegrationTest() fail

### ISSUE THREAD

**Issue by vingorius** [PharmGKB/vcf-parser#1]
Because of difference of end of line character.
    assertEquals(expectedResult, actualResult);
-->
    assertEquals(expectedResult, actualResult.replace("\r", ""));

**Comment by markwoon** [comment]
Do you have autocrlf set to true?

See https://help.github.com/articles/dealing-with-line-endings/

**Comment by vingorius** [comment]
Tks for your rapid answer. and it works.
